config/routes.rb
Rails.application.routes.draw do

  get 'cash_in', to: 'transactions#new', as: 'cash_in'
  resources :transactions
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # devise_scope :user do
  #     root 'devise/sessions#new', as: :unauthenticated_root
  # end

  devise_scope :user do
    #pass a proc to access user methods https://stackoverflow.com/questions/4753871/how-can-i-redirect-a-users-home-root-path-based-on-their-role-using-devise/4754097#4754097
    authenticated :user, -> (u) {u.admin?} do 
      root 'admin/users#index', as: :authenticated_admin_root
    end
    authenticated :user do 
      root 'stocks#index', as: :authenticated_user_root
    end
  
    root 'devise/sessions#new', as: :unauthenticated_root
  end

  get 'stock', to: 'stocks#show', as: 'stock'
  get 'trade', to: 'stocks#index', as: 'trade'
  post 'stock/buy', to: 'stocks#buy', as: 'stock_buy'
  post 'stock/sell', to: 'stocks#sell', as: 'stock_sell'

  namespace :admin do
    resources :users do
      member do
        patch 'approve'
        patch 'reject'
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
    before_action :authenticate_user!
    before_action :instantiate_client
    
    def index
        @trending = @client.stock_market_list(:iexvolume)
        @stocks = current_user.current_stocks
        @latest_price = {} 
        @stocks.each do |s|
            @latest_price[s.security_symbol] = @client.quote(s.security_symbol).latest_price
        end
    end

    def show
        #Begin and rescue SymbolNotFound error if ticker does not exist
        begin
            @stock = @client.quote(params[:symbol])
        rescue 
            respond_to do |format|
                format.html { redirect_to trade_path, notice: "Sorry, we can't find a stock with that symbol." }
            end
        end
    end

    def buy 
        qty = params[:buy_qty].to_i
        quote = @client.quote(params[:buy_symbol])
        price = quote.latest_price.to_d
        total_cost = qty * price
        balance = current_user.balance == nil ? 0.00 : current_user.balance
        valid = false
        if (balance > total_cost) && qty > 0
            transaction = current_user.transactions.create(
                transaction_type: 'buy',
                security_name: quote.company_name,
                security_symbol: quote.symbol,
                quantity: qty,
                security_price: price,
                total_security_cost: total_cost,
                user_id: current_user.id
            )
            if (transaction && transaction.save) && current_user.current_stocks.find_by(security_symbol: quote.symbol)
                purchased_stock = current_user.current_stocks.find_by(security_symbol: quote.symbol)
                purchased_stock.update(
                    quantity: purchased_stock.quantity + qty,
                    total_security_cost: purchased_stock.total_security_cost + total_cost,
                )
                valid = true 
            else
                purchased_stock = current_user.current_stocks.create(
                    security_symbol: quote.symbol,
                    security_name: quote.company_name,
                    quantity: qty,
                    total_security_cost: total_cost,
                    user_id: current_user.id
                ) 
                valid = true
            end 
        end 
        respond_to do |format|
            #Need to validation .create and .update presence because otherwise, save will throw an error
            if  valid == true 
                current_user.update(
                    balance: balance - total_cost
                )
                format.html { redirect_to request.referrer, notice: "Purchase was successful." }
            elsif balance < total_cost
                format.html { redirect_to request.referrer, notice: "Current account balance is insufficient." }
            elsif qty < 0 
                format.html { redirect_to request.referrer, notice: "Quantity cannot be negative." }
            else
                format.html { redirect_to request.referrer, notice: "Something went wrong with your request." }
            end
        end
    end

    def sell 
        qty = params[:sell_qty].to_i
        quote = @client.quote(params[:sell_symbol])
        price = quote.latest_price.to_d
        total_price = qty * price
        sellable_qty = current_user.current_stocks.find_by(security_symbol: quote.symbol) == nil ? 0 : current_user.current_stocks.find_by(security_symbol: quote.symbol).quantity
        valid = false  
        if (sellable_qty >= qty) && qty > 0
            transaction = current_user.transactions.create(
                transaction_type: 'sell',
                security_name: quote.company_name,
                security_symbol: quote.symbol,
                quantity: -qty,
                security_price: price,
                total_security_cost: -total_price,
                user_id: current_user.id
            )
            if (transaction && transaction.save) 
                purchased_stock = current_user.current_stocks.find_by(security_symbol: quote.symbol)
                purchased_stock.update(
                    quantity: purchased_stock.quantity - qty,
                    total_security_cost: purchased_stock.total_security_cost - ((purchased_stock.total_security_cost / purchased_stock.quantity) * qty)
                )
                valid = true 
            end 
        end 
        respond_to do |format|
            if valid == true 
                current_user.update(
                    balance: (current_user.balance || 0.00) + total_price
                )
                format.html { redirect_to request.referrer, notice: "Sale was successful." }
            elsif sellable_qty < qty
                format.html { redirect_to request.referrer, notice: "Current stock quantity is insufficient." }
            elsif qty < 0 
                format.html { redirect_to request.referrer, notice: "Quantity cannot be negative." }
            else
                format.html { redirect_to request.referrer, notice: "Something went wrong with your request." }
            end
        end

    end 

    private

    def instantiate_client
        @client = IEX::Api::Client.new()
    end
end

app/views/stocks/index.html.erb
<%= form_with url: stock_path, method: :get do |form| %>
  <%= form.label :symbol, "Search for stock symbol:" %>
  <%= form.text_field :symbol %>
  <%= form.submit "Search", name: nil %>
<% end %>

<h2>Current Portfolio</h2>
<table>
    <thead>
        <tr>
            <th>Stock Name</th>
            <th>Stock Symbol</th>
            <th>Quantity</th>
            <th>Average Price</th>
            <th>Latest Price</th>
            <th>Total Cost</th>
            <th>Total Profit / Loss </th>
            <th>Profit / Loss %</th>
        </tr>
    </thead>
    <tbody>
        <% @stocks.each do |s| %>
            <tr> 
                <td><%= s.security_name %> </td>
                <td><%= s.security_symbol %> </td>
                <td><%= s.quantity %> </td>
                <td><%= number_to_currency(s.total_security_cost / s.quantity) %> </td>
                <td><%= @latest_price[s.security_symbol] %> </td>
                <td><%= number_to_currency(s.total_security_cost) %> </td>
                <td><%= number_to_currency(@latest_price[s.security_symbol] * s.quantity - (s.total_security_cost)) %> </td>
                <td><%= number_to_percentage(( @latest_price[s.security_symbol] - (s.total_security_cost / s.quantity) ) / (s.total_security_cost / s.quantity)) %> </td>
            </tr>
        <% end %>
    </tbody>
</table>
<h2>Trending Stocks</h2>
<table>
    <thead>
        <tr>
            <th>Stock Symbol</th>
            <th>Stock Name</th>
            <th>Latest Price</th>
            <th>Shares Traded on IEX</th>
            <th>1D Price Change</th>
            <th>1D Price Change %</th>
        </tr>
    </thead>
    <tbody>
        <% @trending.each do |t| %>
            <tr> 
                <td><%= t.symbol %> </td>
                <td><%= t.company_name %> </td>
                <td><%= t.latest_price %> </td>
                <td><%= t.iex_volume %> </td>
                <td><%= t.change %> </td>
                <td><%= t.change_percent_s %> </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/stocks/show.html.erb
<table>
    <thead>
        <tr>
            <th>Symbol</th>
            <th>Company Name</th>
            <th>Latest Price</th>
            <th>Shares Traded on IEX</th>
            <th>1D Price Change</th>
            <th>1D Price Change %</th>
        </tr>
    </thead>
    <tbody>
        <tr> 
            <td><%= @stock.symbol %> </td>
            <td><%= @stock.company_name %> </td>
            <td><%= @stock.latest_price %> </td>
            <td><%= @stock.iex_volume %> </td>
            <td><%= @stock.change %> </td>
            <td><%= @stock.change_percent_s %> </td>
        </tr>
    </tbody>
</table>
<p>Current balance: <%= number_to_currency(current_user.balance) %></p>
<%= form_with url: stock_buy_path, method: :post do |form| %>
  <%= form.label :qty, "Quantity:" %>
  <%= form.text_field :buy_qty %>
  <%= form.hidden_field :buy_symbol, value: @stock.symbol %>
  <%= form.submit "Buy", name: nil %>
<% end %>

<%= form_with url: stock_sell_path, method: :post do |form| %>
  <%= form.label :qty, "Quantity:" %>
  <%= form.text_field :sell_qty %>
  <%= form.hidden_field :sell_symbol, value: @stock.symbol %>
  <%= form.submit "Sell", name: nil %>
<% end %>