config/routes.rb
Rails.application.routes.draw do

  get 'cash_in', to: 'transactions#new', as: 'cash_in'
  resources :transactions
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # devise_scope :user do
  #     root 'devise/sessions#new', as: :unauthenticated_root
  # end

  devise_scope :user do
    #pass a proc to access user methods https://stackoverflow.com/questions/4753871/how-can-i-redirect-a-users-home-root-path-based-on-their-role-using-devise/4754097#4754097
    authenticated :user, -> (u) {u.admin?} do 
      root 'admin/users#index', as: :authenticated_admin_root
    end
    authenticated :user do 
      root 'stocks#index', as: :authenticated_user_root
    end
  
    root 'devise/sessions#new', as: :unauthenticated_root
  end

  get 'stock', to: 'stocks#show', as: 'stock'
  get 'trade', to: 'stocks#index', as: 'trade'
  post 'stock/buy', to: 'stocks#buy', as: 'stock_buy'
  post 'stock/sell', to: 'stocks#sell', as: 'stock_sell'

  namespace :admin do
    resources :users do
      member do
        patch 'approve'
        patch 'reject'
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :transactions
  has_many :current_stocks
  validates :email, uniqueness: true,
                  presence: true
  validates :password, length: {minimum: 6}, unless: -> {password.nil?}
  validates :password, presence: true, if: -> {id.nil?}
  validates :full_name, uniqueness: true,
                      presence: true

  def admin?
    type == "Admin"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    class AuthorizationError < StandardError; end
    before_action :authenticate_user!
    before_action :authorize_user! 
    rescue_from AuthorizationError, with: :unauthorized

    before_action :set_user, only: [:show, :edit, :update, :destroy, :approve, :reject]
  
    def show
    end
  
    def index
        @users = Client.all
    end
  
    def new
        @user = Client.new
    end
  
    def create
        @user = Client.create(user_params.merge!(registration_status: "Active"))

        respond_to do |format|
            if @user.save
              ClientMailer.with(user: @user).confirmation_email.deliver_later

              format.html { redirect_to admin_users_path, notice: "Client was successfully created." } #what's the alternative path to redirect? directly using @task doesnt work
              format.json { render :show, status: :created, location: @user }
            else
              format.html { render :new, status: :unprocessable_entity }
              format.json { render json: @user.errors, status: :unprocessable_entity }
            end
        end
    end
  
    def edit
    end
  
    def update
        @user.update(user_params)

        respond_to do |format|
            if @user.save
              format.html { redirect_to edit_admin_user_path(@user.id), notice: "Client was successfully updated." }
              format.json { render :show, status: :created, location: @user }
            else
              format.html { render :new, status: :unprocessable_entity }
              format.json { render json: @user.errors, status: :unprocessable_entity }
            end
        end
    end
  
    def destroy
        @user.destroy
    end
  
    def approve
        @user.update(registration_status: "Active")
        post_approve_and_reject
    end

    def reject
        @user.update(registration_status: "Reject")
        post_approve_and_reject
    end

    private 

        def post_approve_and_reject
            respond_to do |format|
                if @user.save
                    ClientMailer.with(user: @user).confirmation_email.deliver_later
                    format.html { redirect_to request.referrer, notice: "Client was successfully updated." } 
                else
                    format.html { render :index, status: :unprocessable_entity }
                end
            end
        end

        def set_user
            @user = Client.find(params[:id])
        end
  
        def user_params
            params.require(:client).permit(:email, :password, :password_confirmation, :full_name)
        end

        def authorize_user!
            raise AuthorizationError and return unless current_user.admin?
        end

        def unauthorized
            redirect_to new_user_session_path, notice: 'You are not authorized.'
        end
  end 

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
    if @user.save 
      ClientMailer.with(user: @user).welcome_email.deliver_later
    end
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :full_name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute, :full_name])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/views/admin/users/edit.html.erb
<h2>Edit <%= @user.full_name %></h2>

<%= form_with model: @user, url: admin_user_path(@user.id), method: :patch  do |f| %>

  <div class="field">
    <%= f.label :full_name, "Full Name" %><br />
    <%= f.text_field :full_name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>
  
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/admin/users/index.html.erb
<h2>Current Users<h2>

<table>
    <thead>
        <tr>
            <th>Client Name</th>
            <th>Client Email</th>
            <th>Client Balance</th>
            <th>Client Creation Date</th>
            <th>Client Status</th>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |u| %>
            <tr> 
                <td><%= u.full_name %> </td>
                <td><%= u.email %> </td>
                <td><%= number_to_currency(u.balance) %> </td>
                <td><%= u.created_at %> </td>
                <td><%= u.registration_status %> </td>
                <td><%= link_to "Edit", edit_admin_user_path(u.id) %><td>
                <td><%= link_to "Approve", approve_admin_user_path(u.id), method: :patch  %> </td>
                <td><%= link_to "Reject", reject_admin_user_path(u.id), method: :patch  %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<%=link_to "Create User", new_admin_user_path  %>

app/views/admin/users/new.html.erb
<h2>Sign up</h2>

<%= form_with model: @user, url: :admin_users do |f| %>

  <div class="field">
    <%= f.label :full_name, "Full Name" %><br />
    <%= f.text_field :full_name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>