config/routes.rb
Rails.application.routes.draw do

  get 'cash_in', to: 'transactions#new', as: 'cash_in'
  resources :transactions
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # devise_scope :user do
  #     root 'devise/sessions#new', as: :unauthenticated_root
  # end

  devise_scope :user do
    #pass a proc to access user methods https://stackoverflow.com/questions/4753871/how-can-i-redirect-a-users-home-root-path-based-on-their-role-using-devise/4754097#4754097
    authenticated :user, -> (u) {u.admin?} do 
      root 'admin/users#index', as: :authenticated_admin_root
    end
    authenticated :user do 
      root 'stocks#index', as: :authenticated_user_root
    end
  
    root 'devise/sessions#new', as: :unauthenticated_root
  end

  get 'stock', to: 'stocks#show', as: 'stock'
  get 'trade', to: 'stocks#index', as: 'trade'
  post 'stock/buy', to: 'stocks#buy', as: 'stock_buy'
  post 'stock/sell', to: 'stocks#sell', as: 'stock_sell'

  namespace :admin do
    resources :users do
      member do
        patch 'approve'
        patch 'reject'
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoonTradeFull</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="margin: 0">
  <% if user_signed_in? %>
    <div style="display:flex; align-items:center; margin: 20px 10px">
      <p style="margin: 0 auto 0 10px">MoonTrade</p>
      <div style="margin: 0 10px 0 auto">
        <% if current_user.admin? %> 
          <%= link_to 'Users', admin_users_path %>
        <% else %>        
          <%= link_to 'Cash-In', cash_in_path %>
          <%= link_to 'Trade', trade_path %>
          <%= link_to 'Transactions', transactions_path %>
        <% end %> 
        <% if user_signed_in? %> <%= link_to 'Logout', destroy_user_session_path, method: :delete %> <% end %>
      </div>
    </div>
  <% end %>
    <% if flash[:alert] %>
      <div class='alert alert-danger' style="margin:10px 50px; color: red"><%= flash[:alert] %></div>
    <% end %>
    <p id="notice" style="margin:10px 50px"><%= notice %></p>
    <div style="width: 80%; margin: auto"> <%= yield %> </div>
  </body>
</html>